### ISSUE TITLE
Choosing "military housing" should not require explanation

### ISSUE THREAD

**Issue by ryanhofdotgov** [18F/e-QIP-prototype#576]
**What did you do?**

Fill out a residence, specify it as military housing.

**What did you expect to see?**

Not to have to justify military housing.

**What did you see instead?**

Required field with heading "Please provide an explanation".

**Additional Information**

<img width="649" alt="screen shot 2018-07-17 at 10 49 49 am" src="https://user-images.githubusercontent.com/37100189/42836257-6140cde0-89af-11e8-91d3-d04fff5621dc.png">

**Comment by christopherhuii** [comment]
@ryanhofdotgov I think this is fixed. I cannot reproduce this issue.

**Comment by hursey013** [comment]
@christopherhuii I am still seeing it. This looks to be the source of the issue https://github.com/18F/e-QIP-prototype/blob/develop/src/components/Section/History/Residence/ResidenceItem.jsx#L333-L353

**Comment by christopherhuii** [comment]
@hursey013 I might be looking in the wrong section of the form. Could you provide the location of the field?

I am looking at  Section: History, Subsection: Residence.
![screen shot 2018-10-09 at 10 57 30 am](https://user-images.githubusercontent.com/8367504/46688395-2169d000-cbb2-11e8-88c8-4b519eafcd62.png)

**Comment by hursey013** [comment]
@christopherhuii I think you've got it - in the above screenshot `Please provide an explanation` should not be visible when `Military housing` is selected. In fact it looks like the explanation field should only be present when `Other` is selected:

<img width="759" alt="screen shot 2018-10-09 at 2 04 53 pm" src="https://user-images.githubusercontent.com/1178494/46688765-2f2c4f00-cbcc-11e8-8ff9-a32f5fbacb7f.png">

**Comment by christopherhuii** [comment]
@hursey013 Ohhhhh I see. I thought the issue was to make the field not required. But rather, the explanation field should not show up at all. It should only show up when `Other` is selected.

Thanks for pulling up the form. I didn't think to pull it up for reference.
